# Site settings
title: Jon Hernandez
twitter_username: JonTehKnight
name: Jon Hernandez

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 # - title: Blog
   # url: http://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/J0nTheknight
 - title: StackOverflow
   url: http://stackoverflow.com/users/11694693/jon-hernandez
 # - title: DZone
   # url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/jon-hernandez-38850668/

#Any buzzword skills you want to include
skills:
 - Java
 - Hard Working
 - Adapatable
 - Versatile
 - Willing to Learn Anything
 - Resourceful
 

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Computer Science Student
   start: 2017
   end: Ongoing
   employer: University of Central Florida
   description: Ongoing studies as a fulltime student at UCF
 - title: Weather Journeyman
   start: 2015
   end: 2017
   employer: United States Air Force, 618th Air Operations Center (TACC)
   description: Monitored and compiled climatological data from five operational weather squadrons in support of the 618th AOC missions. Made daily real-time weather threat assesments to ensure the safety of air crews and protection of assets to include aircraft and cargo worth 100-300 million.
 - title: Weather Apprentice
   start: 2012
   end: 2015
   employer: United States Air Force, 15th Operational Weather Squadron
   description: Worked to provide installation forecasts, aviation hazard decision aids, flight weather briefings, and weather advisories, watches and warnings; all for 24 states in northeastern CONUS.
   

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2021 
   subject: Computer Science
   school: University of Central Florida [In Progress]

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - robhinds/robhinds.github.io
 - robhinds/ScaLambda
 - robhinds/opinionated-akka-http
 - robhinds/food2vec
 - robhinds/microservices
 - robhinds/spring-social-geeklist
 - robhinds/spring-social-stackoverflow
 - robhinds/genotype
 - robhinds/footweets
 - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/11694693/jon-hernandez
   flairimageurl: http://stackoverflow.com/users/flair/11694693.png

intro: |
  I am a Computer Science student and a Veteran. I am an entry level programmer with a desire to learn and grow. <br/><br/>
  I enjoy taking on new challenges and learning from those around me. Clean code is something I strive to create in every project I work on, even personal projects.<br/><br/>
  I have worked as a Weather Technician in the Air Force. Managing risk and making sure to look at the big picture are things I've learned in this role that I feel make me valuable memeber of any team. I was trained in 6 different positions alloowing me to be among the most versatile members of the team. 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Java</strong>: My studies have mainly focused on using Java to tackle OOP-based problems. Currently learning everything I can find that is Java based to take these lessons into more languages and concepts.
   <strong>Critical Problem Solving</strong> - I've made many threat based decisions to protect assets and personnel. Including tornado warnings to allow people to shelter in place. One such event required me me to issue a tornado warning for my own base. I stayed behind to monitor the tornado and ensure the warning was properly recieved and acted on.<br/><br/>
   <strong>Quality Assurance Manager</strong> - I was the QA Manager for my unit during my time with the 618th AOC. During my time as QA manager errors in forecasts was reduced by 50% by revamped our QA process and ensuring there was proper accountability and feedback.<br/><br/>
   <strong>Versatile and Trainable</strong> - I was trained in 6 different positions with different responsibilities over my years in the Air Force. Weather Forecaster, Points Forecaster, Weather Floor Manager, Mission Weather Services, Weather Graphics Forecaster, Flight Weather Briefer. This allowed me to be a very versatile member of my team.<br/><br/>
   <strong>Punctual and Dependable</strong> - For 5.5 Years in my time in the air force I never once missed a deadline or commitment in my duties. 
